### ISSUE TITLE
[Bug] Planetdp and turkcealtyazi kodi add-on

### ISSUE THREAD

**Issue by kuafor41** [hbiyik/repository.biyik#3]
Hello Hüseyin,

Above mentioned plug-in's last versions are not working with kodi 19 "matrix" version, could you please so kind to update them to be align with the new version of kodi ?

**Comment by hbiyik** [comment]
hallederiz :)

duplicate: https://github.com/hbiyik/repository.biyik/issues/4

**Comment by kuafor41** [comment]
Adamsın ;)

8 Haz 2021 Sal 12:36 tarihinde Hüseyin BIYIK ***@***.***>
şunu yazdı:
