### ISSUE TITLE
Planetdb Kodi 19

### ISSUE THREAD

**Issue by anonymcoding** [hbiyik/repository.biyik#4]
Opensubtitles da olmayan altyazıları sayende planetdbden bulabiliyordum, matrix desteği de getirirsen çok sevap işlersin

**Comment by hbiyik** [comment]
matrix gelcek, ama ben bu addonu Corelec'te kullaniyorum, corelec hala matrixe gecmedigi icin erteliyorum / useniyorum, yapcam bi ara

**Comment by hbiyik** [comment]
Kodi19 now supported
