### ISSUE TITLE
turkcealtyazi.org addon kodi 19

### ISSUE THREAD

**Issue by psychovsky** [hbiyik/repository.biyik#5]
Lütfen eski turkcealtyazi.org addonunuzu  matrix için tekrar yazın. şu hayatta daha çok dilediğim az şey vardır. kodi 17.6 hata eseri silinmeseydi düne kadar desteği olmamasına rağmen harika çalışıyordu. pandemide evde oturan bizler için, türk kodi kullanıcıları için. Ne destek gerekiyorsa yapmaya hazırım.

**Comment by hbiyik** [comment]
https://forum.kodi.tv/showthread.php?tid=309678&pid=2987237#pid2987237

turkce altyazi kodi 18de de calismiyor, cloudflare protection eklediler bu yuzden daha fazla maintain etmiyecegim bu addonu, planetdb kullanabilirsin 19a gelince.
