### ISSUE TITLE
Need help with vods

### ISSUE THREAD

**Issue by ohmichael** [hbiyik/repository.biyik#6]
Some reason this addon is acting like a matrix addon when it clearly has no instructions to require python version 3.0.0 but when I manually add it to kodi 18 it works but errors out upon open - do you have the version before this newly released one or any version of plugin.video.vods because this other person updated their movie extensions and it won’t work unless vods does - please and thank you.

**Comment by hbiyik** [comment]
Last night i added Kodi19 support. Repo should work both from Kodi18 and Kodi19 at the same time. There was a bug in the first release, and fixed it in 0.1.1 release of tinyxbmc.

When you do another update it should work, if not please provide a log with debug logging enabled i Will fix it

**Comment by ohmichael** [comment]
It works now something must of changed in the zip it kept saying not compatible with version 3.0.0 but when you read this you may close it - I love the work you do.

**Comment by hbiyik** [comment]
enjoy, checkout https://github.com/boogieeeee/repository.boogie as well which are based on vods ;)
