### ISSUE TITLE
Turkce Altyazi Hata

### ISSUE THREAD

**Issue by anonymcoding** [hbiyik/repository.biyik#7]
Planet dp kullanıyordum fakat anlık hata veriyor, siteleri de çökmüş sanırsam ondan kaynaklı, bu yüzden turkcealtyazi eklentisini yukleyeyim dedim ama yüklenmiyor script.module.chromium bulunamadı hatası veriyor.İlgilenebilirsen sevinirim.

**Comment by hbiyik** [comment]
Turkcealtyazi sadece linuxte calisiyor, site CloudFlare DDos Protectiona gectigi icin, arka tarafta bir browser acip bu guvenlik onlemini bypass etmek gerekiyor, bu yuzden script.module.chromium gerekli. Fakat bu addonu sadece Linxute calistirmak mumkun (docker sayesinde). Muhtemelen sen android kullaniyorsun

PlanetDP bu aralar calisiyor olmasi lazim

**Comment by anonymcoding** [comment]
Sorun yok çalışıyor siteleri çökmüştü ondan hata veriyordu, alternatif olarak turkcealtyazi yuklemek istemiştim o yüzden.
